// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace ScoreoidPortable.Entities
{
    internal class GameResponse
    {
        [JsonProperty("Game")]
        public Game Game { get; set; }
    }
}
