// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace ScoreoidPortable.Entities
{
    public class Player
    {
        [JsonProperty("username")]
        public string Username { get; set; }

        [JsonProperty("unique_id")]
        public string UniqueId { get; set; }

        [JsonProperty("first_name")]
        public string FirstName { get; set; }

        [JsonProperty("last_name")]
        public string LastName { get; set; }

        [JsonProperty("email")]
        public string Email { get; set; }

        [JsonProperty("bonus")]
        public int Bonus { get; set; }

        [JsonProperty("achievements")]
        public string Achievements { get; set; }

        [JsonProperty("gold")]
        public int Gold { get; set; }

        [JsonProperty("money")]
        public int Money { get; set; }

        [JsonProperty("kills")]
        public int Kills { get; set; }

        [JsonProperty("lives")]
        public int Lives { get; set; }

        [JsonProperty("time_played")]
        public int TimePlayed { get; set; }

        [JsonProperty("unlocked_levels")]
        public string UnlockedLevels { get; set; }

        [JsonProperty("unlocked_items")]
        public string UnlockedItems { get; set; }

        [JsonProperty("inventory")]
        public string Inventory { get; set; }

        [JsonProperty("last_level")]
        public string LastLevel { get; set; }

        [JsonProperty("current_level")]
        public string CurrentLevel { get; set; }

        [JsonProperty("current_time")]
        public int CurrentTime { get; set; }

        [JsonProperty("current_bonus")]
        public int CurrentBonus { get; set; }

        [JsonProperty("current_kills")]
        public int CurrentKills { get; set; }

        [JsonProperty("current_achievements")]
        public string CurrentAchievements { get; set; }

        [JsonProperty("current_gold")]
        public int CurrentGold { get; set; }

        [JsonProperty("current_unlocked_levels")]
        public int CurrentUnlockedLevels { get; set; }

        [JsonProperty("current_unlocked_items")]
        public string CurrentUnlockedItems { get; set; }

        [JsonProperty("current_lives")]
        public int CurrentLives { get; set; }

        [JsonProperty("xp")]
        public string Xp { get; set; }

        [JsonProperty("energy")]
        public string Energy { get; set; }

        [JsonProperty("boost")]
        public string Boost { get; set; }

        [JsonProperty("latitude")]
        public string Latitude { get; set; }

        [JsonProperty("longtitude")]
        public string Longtitude { get; set; }

        [JsonProperty("game_state")]
        public string GameState { get; set; }

        [JsonProperty("platform")]
        public string Platform { get; set; }

        [JsonProperty("rank")]
        public int Rank { get; set; }

        [JsonProperty("best_score")]
        public int BestScore { get; set; }

        [JsonProperty("created")]
        public string Created { get; set; }

        [JsonProperty("updated")]
        public string Updated { get; set; }
    }
}
