// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using Newtonsoft.Json;
using PropertyChanged;
using ScoreoidPortable.Attributes;

namespace ScoreoidPortable.Entities
{
    [ImplementPropertyChanged]
    public class Score
    {
        [JsonProperty("id"), Description("id")]
        public string Id { get; set; }

        [JsonProperty("player_id"), Description("player_id")]
        public string PlayerId { get; set; }

        [JsonProperty("difficulty"), Description("difficulty")]
        public int Difficulty { get; set; }

        [JsonProperty("platform"), Description("platform")]
        public string Platform { get; set; }

        [JsonProperty("leaderboard"), Description("leaderboard")]
        public object Leaderboard { get; set; }

        [JsonProperty("data"), Description("data")]
        public string Data { get; set; }

        [JsonProperty("score"), Description("score")]
        public string TheScore { get; set; }

        [JsonProperty("game_id"), Description("game_id")]
        public string GameId { get; set; }

        [JsonProperty("created"), Description("created")]
        public DateTime CreatedDate { get; set; }
    }
}

