// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using Newtonsoft.Json;

namespace ScoreoidPortable.Entities
{
    public class Score
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("player_id")]
        public string PlayerId { get; set; }

        [JsonProperty("difficulty")]
        public int Difficulty { get; set; }

        [JsonProperty("platform")]
        public string Platform { get; set; }

        [JsonProperty("leaderboard")]
        public object Leaderboard { get; set; }

        [JsonProperty("data")]
        public object Data { get; set; }

        [JsonProperty("score")]
        public string TheScore { get; set; }

        [JsonProperty("game_id")]
        public string GameId { get; set; }

        [JsonProperty("created")]
        public DateTime Created { get; set; }
    }

    public class ScoreArray
    {
        [JsonProperty("Score")]
        public Score Scores { get; set; }
    }
}

